assert.throws(ReferenceError, function() {
  {
    x; const x = 1;
  }
});