assert.throws(ReferenceError, function() {
  {
    const x = x + 1;
  }
});